general {
    lock_cmd = pgrep -x hyprlock > /dev/null || hyprlock
    before_sleep_cmd = loginctl hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Listener 1: Lock the screen (20 minutes)
listener {
    timeout = 1200
    on-timeout = hyprlock
}

# Listener 2: Turn off the displays (30 minutes)
listener {
    timeout = 1800
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Listener 3: Suspend the system (45 minutes)
listener {
    timeout = 2700
    on-timeout = systemctl suspend
}

# Kanshi refresh
listener {
    timeout = 10
    on-resume = pkill kanshi; sleep 0.5; kanshi
}
