general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Listener 1: Lock the screen (20 minutes)
listener {
    timeout = 1200
    on-timeout = loginctl lock-session
}

# Listener 2: Turn off the displays (30 minutes)
listener {
    timeout = 1800
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Listener 3: Suspend the system (45 minutes)
listener {
    timeout = 2700
    on-timeout = systemctl suspend
}

# Kanshi refresh
listener {
    timeout = 10
    on-resume = sh -c "pkill kanshi; kanshi &"
}
